# Generated by Django 4.1.7 on 2023-02-21 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Document_name', max_length=255)),
                ('date', models.DateField()),
                ('myfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pcap'])])),
            ],
        ),
    ]
